
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pv-claim
  labels:
    app: php-webserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-webserver
spec:
  selector:
    matchLabels:
      app: php-webserver
  template:
    metadata:
      labels:
        app: php-webserver
    spec:
      containers:
      - name: php-webserver
        imagePullPolicy: IfNotPresent
        image: vimal13/apache-webserver-php
        ports:
        - containerPort: 80
        volumeMounts:
          - name: php-vol
            mountPath: /var/www/html
      volumes:
          - name: php-vol
            persistentVolumeClaim:
              claimName: php-pv-claim
      volumes:
          - name: php-vol
            hostPath:
              path: /home/docker/php_page
---
apiVersion: v1
kind: Service
metadata:
  name: php-webserver
  labels:
    run: php-webserver
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31515
      protocol: TCP
  selector:
      app: php-webserver
